name: Python CI/CD Secure Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python unit tests (pytest)
      run: pytest

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-secure-app:latest .

    - name: Trivy Scan (Docker image)
      uses: aquasecurity/trivy-action@0.16.0
      with:
        image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/python-secure-app:latest'
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'

    - name: Trivy Scan (Filesystem - Code & Dependencies)
      uses: aquasecurity/trivy-action@0.16.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'

    - name: Snyk Scan (Docker image)
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: '${{ secrets.DOCKERHUB_USERNAME }}/python-secure-app:latest'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-secure-app:latest
